version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make EXE_NAME=httpie-go_linux_amd64
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            GOOS=darwin make EXE_NAME=httpie-go_darwin_amd64
      - run:
          name: Build (win)
          command: |
            GOOS=windows GOARCH=amd64 make EXE_NAME=httpie-go_win_amd64.exe
      - run:
          name: "Publish Release on GitHub"
          command: |
            mkdir pkg bin && cp -aR *amd* pkg/
            curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
            tar -xf upx-3.96-amd64_linux.tar.xz
            cp upx-3.96-amd64_linux/upx bin/
            rm -rf upx-3.96-amd64_linux upx-3.96-amd64_linux.tar.xz
            bin/upx pkg/httpie-go_linux_amd64
            bin/upx pkg/httpie-go_win_amd64.exe
            bin/upx pkg/httpie-go_darwin_amd64
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG_VERSION} ./pkg/


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
